### ISSUE TITLE
Train occupancy on point cloud

### ISSUE THREAD

**Issue by kuynzereb** [computational-imaging/ACORN#2]
Hi!

Is it possible to train occupancy model on point cloud? As I can see, training heavily relies on `OccupancyDataset` which needs a mesh to evaluate occupancy of query points. Is there any workaround to use point clouds or this model can be used for meshes only?

**Comment by davelindell** [comment]
The current implementation requires a mesh so that the occupancy of any data point can be evaluated to supervise the model during training. However, we also considered other approaches that would not require a mesh. While they would probably yield worse shape models (in terms of error wrt ground truth shape), they have the advantage of being trainable directly from a point cloud. These aren't supported in the current code base, but you might consider the following

- a "border" occupancy model where you are given a point cloud of on-surface points. Then, you can train the model by labeling any point within some epsilon ball of a surface point to be occupied and any points outside of that to be non-occupied. We found this works OK, but requires a sufficiently dense point cloud and an efficient sampling method to get enough occupied points near the surface.  

- an SDF-based model where you are given a collection of oriented on-surface points. The on-surface points are trained to represent the zero level set of the point cloud, and the model should be supervised with the eikonal constraint so that it converges to correct values of the SDF off the surface. Note that this also requires a scheme to ensure continuity across the "blocks" of the ACORN model so that the eikonal constraint is satisfied across the blocks. This is the method that we implemented for our previous paper on [SIRENs](https://github.com/vsitzmann/siren).

**Comment by kuynzereb** [comment]
I see, thank you. 

I am interested in the task of mesh reconstruction from [oriented] point clouds. SIREN gives quite decent results even if input points and normals are quite noisy. But it is too memory and time consuming and detalization may be better (as ACORN shows). I hoped that ACORN will kinda fix all these problems, but now understand that in its current form it is not designed for such a task.
