### ISSUE TITLE
Tokyo/mars gigapixel too large, process killed

### ISSUE THREAD

**Issue by xindonglin99** [computational-imaging/ACORN#7]
Hi,

I've tried setting up the ACRON environment to train the Tokyo gigapixel ("tokyo.tif") but I cannot get the process to train after the data loader finished 50%. Even I changed the `PIL.Image.MAX_IMAGE_PIXELS = none` , the process still gets killed due to large memory use. I wonder if you have ever encountered this issue and would like to know how you deal with such a large image without exceeding the memory.

Thanks in advance.

**Comment by xindonglin99** [comment]
It seems it's because the 'res' in the 'config_tokyo.ini' is too high. I adjust it to 8k and it starts training. However, are there some methods that can train using the original resolution in the file? I believe you trained the tokyo image using that resolution.

**Comment by davelindell** [comment]
In the current code we load the entire image into memory, so unfortunately these large images do require a lot of memory.

One simple solution could be to reduce the number of workers since each worker keeps its own copy of the data. Otherwise, it's probably required to load parts of the image from disk at each training iteration, which may be very slow and would require a rewrite of the data loader. 

Can you try decreasing the number of workers?

**Comment by xindonglin99** [comment]
Hi David,

Thanks for the reply. I expressed the wrong memory. It should be the GPU memory, which I believed the `[19456, 51200]` tokyo took around 28GB that exceed 24GB (RTX3090). In the paper, RTX6000 is used so I think there might be some issue as RTX6000 has 24GB memory. I did send the same experiment to Compute Canada using a v100 (32GB), 125G memory for debugging purposes. I found out it trained super slow and cannot finish in ~12hrs as the paper mentioned. I used the default config with the tokyo.tif downloaded as instructed in the 'README.MD' . 

![image](https://user-images.githubusercontent.com/47045176/163435792-564e00fb-fe5c-4add-9d52-1deaed027d74.png)

I will definitely try to reduce the number of workers to see if it helps but it would be nice if I can replicate the experiment you did in the paper. ACORN is the state-of-the-art method that we used as one of our baselines.

**Comment by davelindell** [comment]
I see, thanks for the clarification. We actually used an RTX 8000 for the gigapixel fitting (details in the paper supp.), and this has 48 GB of VRAM. I don't think this config will work with 24 GB of VRAM. It should be possible to lower the VRAM usage by decreasing the patch size (but the patch size 19 is not divisible by 2 in this case, so it would require a different image resolution). Otherwise using a smaller max number of patches should also work.

**Comment by xindonglin99** [comment]
Thanks for the explanation!
