### ISSUE TITLE
How to choose res/patch size for new images

### ISSUE THREAD

**Issue by xindonglin99** [computational-imaging/ACORN#8]
Hi,

Currently, I want to run ACORN for several new images. We encountered an issue with this image 
![reference](https://user-images.githubusercontent.com/47045176/163440685-8225791f-4326-46af-a874-dd482d321730.jpg)

that has '3250 x 4333' res. Since 3250 and 4333 has no common factor, I don't know how to choose patch size for that. I tried to resize it with the following config 
![image](https://user-images.githubusercontent.com/47045176/163440874-994cdee8-df6f-4638-a58b-9126ad2ffeaa.png)

but during the training, we encountered an unexpected error related to tensor shapes:

![image](https://user-images.githubusercontent.com/47045176/163441023-587cff64-a198-454c-b7ec-aaa021cfce96.png)

Any idea why this happened? Thanks in advance.

**Comment by davelindell** [comment]
The image needs to be at a resolution that subdivides down to the value given for `patch_size` where `patch_size` is [num_channels, patch_y_res, patch_x_res]. 

So if your image is [4096, 3250] at the top level of the quadtree, at the next lower level it would be [4096/2, 3250/2], and so on down to [patch_y_res, patch_x_res] after some number of levels.

In this case, you have roughly 7 levels since 4096 / 2**7 = 32. But 3250 / 2**7 doesn't divide evenly. You could have 24*2**7 = 3072 as the image horizontal resolution, though, since that would divide evenly. This could be done by simply cropping the high-resolution image to be [4096, 3072] resolution.

**Comment by xindonglin99** [comment]
Thanks for your advice. We changed the resolution to [4096, 3072] which has the same proportion for height and width but it still caused some errors. We can finish the training phase, but during the evaluation that generates the image, we encounter the following issue

> Traceback (most recent call last):
  File "train_img.py", line 359, in <module>
    main()
  File "train_img.py", line 198, in main
    run_eval(model, coord_dataset)
  File "train_img.py", line 310, in run_eval
    psnr, ssim = get_metrics(display_pred, display_gt)
  File "train_img.py", line 344, in get_metrics
    p = pred_img.transpose(1, 2, 0)
ValueError: axes don't match array
free(): invalid pointer
Aborted (core dumped)

Sometimes we encounter the former issue that I mentioned in the previous comment

![image](https://user-images.githubusercontent.com/47045176/163441023-587cff64-a198-454c-b7ec-aaa021cfce96.png)

I think it might be some reasons caused by the strict constraints of the input images. Any suggestion in this case? Appreciate your help!
